import React, { useEffect, useState } from 'react';

function ChatbotResult({ langData }) {
    const [latestData, setLatestData] = useState(null);
    
    // --- SIMULATED ML & GEMINI RESPONSE DATA ---
    const SIMULATED_PREDICTION = "45.2"; 
    const SIMULATED_ADVICE = 
        "Namaste kisan bhai/behan! Aapke Rice fasal ke liye Flowering stage mein, humari prediction hai ki aapki upaj (yield) 45.2 quintals/acre ho sakti hai. Aapne Disease ki samasya batayi hai, iske liye aap turant [Fungicide X] ka chhidkav karein aur agle 5 dinon tak paani na de. Aapka prediction achha hai, bas beemari ko control karein. (Note: This simulated response is derived directly from our Colab ML Notebook's generated prompt.)";
    // --- END SIMULATED DATA ---

    // Load the latest data from Local Storage
    useEffect(() => {
        const storedData = JSON.parse(localStorage.getItem('krishiSakhiData'));
        if (storedData && storedData.length > 0) {
            setLatestData(storedData[storedData.length - 1]);
        }
    }, []);

    if (!latestData) {
        return <div className="text-center text-lg text-gray-500 py-20">Loading results...</div>;
    }

    return (
        <div className="flex justify-center py-12 px-4">
            <div className="w-full max-w-4xl">
                
                <h2 className="text-4xl font-bold text-green-700 mb-6 text-center">
                    {langData.heroTitle} ({langData.submitBtn} Done!)
                </h2>

                <div className="p-8 bg-white rounded-xl shadow-2xl border-t-4 border-green-600">
                    <h3 className="text-2xl font-bold mb-4 flex items-center text-green-800">
                        <i className="fa-solid fa-robot mr-3"></i> KrishiSakhi AI ka Jawab
                    </h3>
                    
                    <div className="mb-6 p-4 bg-green-50 rounded-lg">
                        <p className="text-xl font-semibold text-green-800">
                            📈 **ML Prediction:** Estimated Yield is **{SIMULATED_PREDICTION} quintals/acre**.
                        </p>
                        <p className="text-sm text-gray-600 mt-1">
                            (Based on your submission: Crop: {latestData.crop}, Problem: {latestData.problem})
                        </p>
                    </div>

                    <h4 className="text-lg font-bold mb-3">Personalized Advice from Gemini:</h4>
                    <p className="text-base leading-relaxed whitespace-pre-wrap">
                        {SIMULATED_ADVICE}
                    </p>
                    
                    <p className="mt-6 text-sm italic text-gray-600">
                        *Note: This response demonstrates the secure, data-driven advice generated by the Gemini API using your ML model's prediction.*
                    </p>
                </div>
                
                {/* Voice Input Section Re-Simulated for Chatbot Page */}
                <div className="mt-8 p-6 rounded-xl border border-gray-300 bg-white shadow-lg">
                    <h4 className="text-xl font-semibold text-green-600 mb-4">Ask a Follow-up Question:</h4>
                    {/* Placeholder for future Chat Interface */}
                    <textarea 
                        className="w-full p-3 border border-gray-300 rounded-lg resize-none focus:ring-green-500" 
                        rows="3" 
                        placeholder="Type your question here, or use the microphone..."
                    ></textarea>
                    <button className="bg-green-500 text-white font-bold py-2 px-4 rounded-lg mt-2 hover:bg-green-600">
                        Send Query
                    </button>
                </div>
            </div>
        </div>
    );
}

export default ChatbotResult;
